<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Library</OutputType>
		<RootNamespace>Lattice</RootNamespace>
		<AssemblyName>Lattice.Terminal</AssemblyName>
		<TargetFramework>net48</TargetFramework>
		<SupportedOSPlatform>windows</SupportedOSPlatform>
		<LangVersion>preview</LangVersion>
		<ImplicitUsings>disable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

</Project>